package com.claim.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * 2014-10-01T16:44:13.158+05:30
 * Generated source version: 2.7.11.redhat-3
 * 
 */
@WebService(targetNamespace = "localhost:8080/ClaimsService/", name = "ClaimsService")
@XmlSeeAlso({ObjectFactory.class})
public interface ClaimsService {

    @RequestWrapper(localName = "fileNewClaim", targetNamespace = "localhost:8080/ClaimsService/", className = "com.claim.service.FileNewClaim")
    @WebMethod(action = "fileNewClaim")
    @ResponseWrapper(localName = "fileNewClaimResponse", targetNamespace = "localhost:8080/ClaimsService/", className = "com.claim.service.FileNewClaimResponse")
    public void fileNewClaim(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "policyHolderDetails", targetNamespace = "")
        com.claim.service.PolicyHolderDetailsType policyHolderDetails,
        @WebParam(name = "vehicleDetails", targetNamespace = "")
        com.claim.service.VehicleDetailsType vehicleDetails,
        @WebParam(name = "accidentDetails", targetNamespace = "")
        com.claim.service.AccidentDetailsType accidentDetails,
        @WebParam(name = "driverDetails", targetNamespace = "")
        com.claim.service.DriverDetailsType driverDetails,
        @WebParam(mode = WebParam.Mode.OUT, name = "claimsID", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> claimsID,
        @WebParam(mode = WebParam.Mode.OUT, name = "result", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> result
    );

    @WebResult(name = "claims", targetNamespace = "")
    @RequestWrapper(localName = "getExistingClaims", targetNamespace = "localhost:8080/ClaimsService/", className = "com.claim.service.GetExistingClaims")
    @WebMethod(action = "getExistingClaims")
    @ResponseWrapper(localName = "getExistingClaimsResponse", targetNamespace = "localhost:8080/ClaimsService/", className = "com.claim.service.GetExistingClaimsResponse")
    public java.util.List<com.claim.service.ClaimsType> getExistingClaims(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    );
}
