package localhost._8080.claimsservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * 2014-11-14T15:25:30.652+05:30
 * Generated source version: 2.7.11.redhat-3
 * 
 */
@WebService(targetNamespace = "localhost:8080/ClaimsService/", name = "ClaimsService")
@XmlSeeAlso({localhost._8080.claimsservice.policyholderdetails.ObjectFactory.class, localhost._8080.claimsservice.accidentdetails.ObjectFactory.class, localhost._8080.claimsservice.driverdetails.ObjectFactory.class, ObjectFactory.class, localhost._8080.claimsservice.vehicledetails.ObjectFactory.class})
public interface ClaimsService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateExistingClaims", targetNamespace = "localhost:8080/ClaimsService/", className = "localhost._8080.claimsservice.UpdateExistingClaims")
    @WebMethod(action = "updateExistingClaims")
    @ResponseWrapper(localName = "updateExistingClaimsResponse", targetNamespace = "localhost:8080/ClaimsService/", className = "localhost._8080.claimsservice.UpdateExistingClaimsResponse")
    public boolean updateExistingClaims(
        @WebParam(name = "claimId", targetNamespace = "")
        java.lang.String claimId,
        @WebParam(name = "policeStationName", targetNamespace = "")
        java.lang.String policeStationName,
        @WebParam(name = "FIRNo", targetNamespace = "")
        java.lang.String firNo
    );

    @RequestWrapper(localName = "fileNewClaim", targetNamespace = "localhost:8080/ClaimsService/", className = "localhost._8080.claimsservice.FileNewClaim")
    @WebMethod(action = "fileNewClaim")
    @ResponseWrapper(localName = "fileNewClaimResponse", targetNamespace = "localhost:8080/ClaimsService/", className = "localhost._8080.claimsservice.FileNewClaimResponse")
    public void fileNewClaim(
        @WebParam(name = "policyHolderDetails", targetNamespace = "")
        localhost._8080.claimsservice.policyholderdetails.PolicyHolderDetailsType policyHolderDetails,
        @WebParam(name = "vehicleDetails", targetNamespace = "")
        localhost._8080.claimsservice.vehicledetails.VehicleDetailsType vehicleDetails,
        @WebParam(name = "accidentDetails", targetNamespace = "")
        localhost._8080.claimsservice.accidentdetails.AccidentDetailsType accidentDetails,
        @WebParam(name = "driverDetails", targetNamespace = "")
        localhost._8080.claimsservice.driverdetails.DriverDetailsType driverDetails,
        @WebParam(mode = WebParam.Mode.OUT, name = "claimsID", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> claimsID,
        @WebParam(mode = WebParam.Mode.OUT, name = "result", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> result
    );

    @WebResult(name = "claims", targetNamespace = "")
    @RequestWrapper(localName = "getExistingClaims", targetNamespace = "localhost:8080/ClaimsService/", className = "localhost._8080.claimsservice.GetExistingClaims")
    @WebMethod(action = "getExistingClaims")
    @ResponseWrapper(localName = "getExistingClaimsResponse", targetNamespace = "localhost:8080/ClaimsService/", className = "localhost._8080.claimsservice.GetExistingClaimsResponse")
    public java.util.List<localhost._8080.claimsservice.ClaimsType> getExistingClaims(
        @WebParam(name = "policyId", targetNamespace = "")
        java.lang.String policyId
    );
}
