package com.claims.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * 2014-11-03T00:09:15.576+05:30
 * Generated source version: 2.7.11.redhat-3
 * 
 */
@WebServiceClient(name = "ClaimsService", 
                  wsdlLocation = "file:/Users/vikask/Documents/workspace/ClaimsServiceProject/WebContent/WEB-INF/wsdl/ClaimsService.wsdl",
                  targetNamespace = "localhost:8080/ClaimsService/") 
public class ClaimsService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("localhost:8080/ClaimsService/", "ClaimsService");
    public final static QName ClaimsServiceSOAP = new QName("localhost:8080/ClaimsService/", "ClaimsServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/vikask/Documents/workspace/ClaimsServiceProject/WebContent/WEB-INF/wsdl/ClaimsService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ClaimsService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/vikask/Documents/workspace/ClaimsServiceProject/WebContent/WEB-INF/wsdl/ClaimsService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ClaimsService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ClaimsService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClaimsService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClaimsService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClaimsService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ClaimsService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ClaimsService
     */
    @WebEndpoint(name = "ClaimsServiceSOAP")
    public ClaimsService getClaimsServiceSOAP() {
        return super.getPort(ClaimsServiceSOAP, ClaimsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClaimsService
     */
    @WebEndpoint(name = "ClaimsServiceSOAP")
    public ClaimsService getClaimsServiceSOAP(WebServiceFeature... features) {
        return super.getPort(ClaimsServiceSOAP, ClaimsService.class, features);
    }

}
